### ISSUE TITLE
HD skins support

### ISSUE THREAD

**Issue by Andrey96** [earthiverse/3D-Minecraft-Skin-Viewer#12]
Supporting HD skins (for example 256x128) would be very cool! Maybe it's enough to change only skin2d.js

**Comment by earthiverse** [comment]
Sorry, I missed this a while ago.
It should be pretty simple, yeah. In fact, it might be as simple as multiplying all of the numbers in 2dskin.js by the ratio between the new skin size and the original.

256/64 = 4, so if you multiply all numbers by 4, it should be good to go. I'm trying to do the math in my head, but I think it's that easy...

Do you have an example of an HD skin?

**Comment by Andrey96** [comment]
Oh, I already done it for myself. Here you can see what I changed (website is for my private server):
http://ultramc.ru/2dskin.js
http://ultramc.ru/3dskin.js (cut from your index.html)
My changes are really hacky, but they were done really fast and are working for me.
In short, I just added var 'sc' that means scale (automatically computed as height/32) and applied it on everything in 2dskin.js and something in 3dskin.js
Maybe you'll find more elegant way to do this.

Here I made a sample page with modified code:
http://ultramc.ru/skin_sample.html

**Comment by earthiverse** [comment]
That sounds plenty elegant :+1: :)
Can't really do much better than that.
