### ISSUE TITLE
Re-license to LGPL or MIT

### ISSUE THREAD

**Issue by g-plane** [earthiverse/3D-Minecraft-Skin-Viewer#20]
This library is wonderful. However it is licensed under GPL. It isn't convenient for others to use this library but licensed under other license. I suggest to re-license this project to LGPL or MIT. (MIT is most popular for many JavaScript projects.)

**Comment by earthiverse** [comment]
Okay, it's MIT now.

**Comment by g-plane** [comment]
Thanks!
