### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by LowScarlet** [earthiverse/3D-Minecraft-Skin-Viewer#22]
How to use this?

**Comment by earthiverse** [comment]
Download the code as a zip, then open index.html in a modern browser.

You can no longer use a username, but if you put in your UUID, which you can get from [https://mcuuid.net/?q=earthiverse](https://mcuuid.net/?q=earthiverse), it still works.


![image](https://user-images.githubusercontent.com/602905/129314650-6591990a-ed4c-43c5-bdd7-6d32d30161aa.png)
