### ISSUE TITLE
Render

### ISSUE THREAD

**Issue by McKay1717** [earthiverse/3D-Minecraft-Skin-Viewer#9]
Hello I have a problem , i think it's caused by my server configuration , can you give what is needed (PHP , Permission , etc)

My Page : http://render.darkube.net/index.php?u=chkponey
My Custom Skin Serv : http://skin.darkube.net/chkleponey.png

McKay ;)

**Comment by earthiverse** [comment]
I'd suggest taking a look at the new code, it's javascript instead of php.
It requires no special server side stuff :)

Download the repository as a .zip and extract it to your desktop, then open index.html in the web browser of your choice to check it out.
